"""add_finance_module

Revision ID: cc0d2c6e2dfb
Revises: 0001_initial
Create Date: 2026-02-28 00:54:33.582159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc0d2c6e2dfb'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_code', name='uq_accounts_tenant_code')
    )
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_index('ix_accounts_tenant_id_code', 'accounts', ['tenant_id', 'account_code'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closing_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['closing_entry_id'], ['journal_entries.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_years_tenant_id'), 'fiscal_years', ['tenant_id'], unique=False)
    op.create_index('ix_fiscal_years_tenant_id_status', 'fiscal_years', ['tenant_id', 'status'], unique=False)
    op.create_table('journal_entries',
    sa.Column('journal_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('reversal_of', sa.UUID(), nullable=True),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_tenant_id'), 'journal_entries', ['tenant_id'], unique=False)
    op.create_index('ix_journal_entries_tenant_id_date', 'journal_entries', ['tenant_id', 'posting_date'], unique=False)
    op.create_table('tax_rates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('linked_account_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rates_tenant_id'), 'tax_rates', ['tenant_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_lines_journal_entry', 'journal_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_tenant_id'), 'journal_lines', ['tenant_id'], unique=False)
    op.create_index('ix_journal_lines_tenant_id_account', 'journal_lines', ['tenant_id', 'account_id'], unique=False)
    op.add_column('audit_logs', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('audit_logs', 'metadata')
    op.drop_constraint(op.f('tenants_domain_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('user_roles', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=False)
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_domain_key'), 'tenants', ['domain'], postgresql_nulls_not_distinct=False)
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_logs', 'extra_metadata')
    op.drop_index('ix_journal_lines_tenant_id_account', table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_tenant_id'), table_name='journal_lines')
    op.drop_index('ix_journal_lines_journal_entry', table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_tax_rates_tenant_id'), table_name='tax_rates')
    op.drop_table('tax_rates')
    op.drop_index('ix_journal_entries_tenant_id_date', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_tenant_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_fiscal_years_tenant_id_status', table_name='fiscal_years')
    op.drop_index(op.f('ix_fiscal_years_tenant_id'), table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index('ix_accounts_tenant_id_code', table_name='accounts')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###